config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"

  get 'result', to: 'home#result'

  devise_for :users

  resources :materials
  resources :users
  resources :composite_materials
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
      can :index_materials
    else
      can :manage, :home
      can :index, Material
    end
  end
end

app/models/material.rb
class Material < ActiveRecord::Base

  validates :price, presence: true, numericality: true
  validates :color, presence: true, uniqueness: true

end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable

  enumerize :role, in: {staff: 0, admin: 1}, default: :staff, scope: true, predicates: true

  validates :role, :login, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, alert: "403: 很抱歉，您没有权限去操作该页面！"
  end

  attr_accessor :show_flash

  helper_method :current_session

  protected

    def current_session
      controller_name
    end

    def after_sign_out_path_for scope
      new_user_session_path
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def result
    return render json: {result: 0.0} if params["rs"].blank?

    materials = Material.all

    rs = params["rs"].inject(BigDecimal.new(0)) do |sum, value|
      material = materials.find { |m| m.id.to_s == value[1]["material"].to_s }
      material.nil? ? sum : sum + material.price * value[1]["rate"].to_f
    end

    render json: { result: rs }
  end
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  authorize_resource
  before_action :set_material, only: [:edit, :update, :destroy]

  def index
    @materials = Material.all
    respond_to do |wants|
      wants.json  do
        render json: @materials.map { |m| {label: m.color, value: m.id} }.insert(0, {label: "", value: ""}), root: false
      end
      wants.html do
        authorize! :index_materials, current_user
      end
    end
  end

  def new
    @material = Material.new
  end

  def edit
  end

  def update
    if @material.update_attributes material_params
      redirect_to materials_path, notice: "成功更新原材料：【#{@material.color}】"
    else
      render :edit
    end
  end

  def destroy
    if @material.destroy
      redirect_to materials_path, notice: "成功删除原材料：【#{@material.color}】"
    else
      redirect_to materials_path, alert: "无法删除原材料：【#{@material.color}】"
    end
  end

  def create
    @material = Material.new material_params

    if @material.save
      redirect_to materials_path, notice: "成功添加原材料：【#{@material.color}】"
    else
      render :new
    end
  end

  private
    def material_params
      params.require(:material).permit(:color, :price)
    end

    def set_material
      @material = Material.find params[:id]
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  authorize_resource

  before_action :set_user, only: [:edit, :update, :destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def edit
  end

  def update
    if @user.update_attributes user_params
      redirect_to users_path, notice: "成功更新用户：【#{@user.login}】"
    else
      render :edit
    end
  end

  def destroy
    if @user.destroy
      redirect_to users_path, notice: "成功删除用户：【#{@user.login}】"
    else
      redirect_to users_path, alert: "无法删除用户：【#{@user.login}】"
    end
  end

  def create
    @user = User.new user_params

    if @user.save
      redirect_to users_path, notice: "成功添加用户：【#{@user.login}】"
    else
      render :new
    end
  end

  private
    def user_params
      params.require(:user).permit(:login, :password, :password_confirmation, :role)
    end

    def set_user
      @user = User.find params[:id]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Devise::TestHelpers

  def nav_li name, url, options = {}
    if can? :manager, name
      cls = current_session == name ? "active" : ""
      content_tag :li, class: cls do
        link_to I18n.translate("nav.li.#{name}"), url, options
      end
    else
      ""
    end
  end
end

app/views/home/index.html.erb
<div class="col-md-6">
  <table id='computer' class='table table-striped'></table>
  <div class='actions'>
    <a class='btn btn-primary' id='append'>新增</a>
    <a class='btn btn-warning' id='compute-result'>计算结果</a>
    <span class='result'>结果为：<strong>0.00</strong>￥</span>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cost</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "首页", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= nav_li "home", root_path %>
        <%= nav_li "materials", materials_path %>
        <%= nav_li "users", users_path %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if current_user %>
          <li><%= link_to "退出", destroy_user_session_path, method: "DELETE" %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% unless controller_name == "sessions" %>
  <div class="flash">
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
  </div>
<% end %>

<div class="container" style='min-height:800px;'>
  <%= yield %>
</div>

</body>
</html>

app/views/materials/_form.html.erb
<div class="col-md-5">
  <%= simple_form_for(@material, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :color, class: "form-control", placeholder: "颜色" %>
    <%= f.input :price, class: "form-control" do %>
      <div class="input-group">
        <span class="input-group-addon">￥</span>
        <%= f.number_field :price, class: "number required form-control" %>
      </div>
    <% end %>
    <div class="form-group">
      <%= f.submit "保存", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/materials/edit.html.erb
<%= render "form" %>

app/views/materials/index.html.erb
<%= link_to "添加新材料", new_material_path %>
<hr />
<div class="row col-md-8">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>颜色</th>
        <th>单价/￥</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @materials.each do |m| %>
        <tr>
          <td><%= m.id %></td>
          <td><%= m.color %></td>
          <td><%= m.price %></td>
          <td>
            <%= link_to "编辑", edit_material_path(m), class: "action action-info" %>
            <%= link_to "删除", material_path(m), class: "action action-danger",
              data: { confirm: "您确定要删除【#{m.color}】么？" }, method: "DELETE" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/materials/new.html.erb
<%= render "form" %>

app/views/users/_form.html.erb
<div class="col-md-5">
  <%= simple_form_for(@user, html: { class: 'form-horizontal' }) do |f| %>
    <%= f.input :login, placeholder: "登录名" %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.input :role do %>
      <%= f.select :role, User.role.options %>
    <% end %>

    <div class="form-group">
      <%= f.submit "保存", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/index.html.erb
<%= link_to "添加新用户", new_user_path %>
<hr />
<div class="row col-md-8">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <th>登录名</th>
        <th>创建时间</th>
        <th>上次登录时间</th>
        <th>操作</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.id %></td>
          <td><%= user.login %></td>
          <td><%= l user.created_at, format: :simple %></td>
          <td><%= l user.last_sign_in_at, format: :simple if user.last_sign_in_at %></td>
          <td>
            <%= link_to "编辑", edit_user_path(user), class: "action action-info" %>
            <%= link_to "删除", user_path(user), class: "action action-danger",
              data: { confirm: "您确定要删除【#{user.login}】么？" }, method: "DELETE" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/new.html.erb
<%= render "form" %>